# Phosphoproteomics experiment configuration
experiments:
  HS:
    dir_proteomics: "HS"
    condition: "HS_phosph"
    norm_opt: "not_norm"
    col_control: "#4f4f4f"
    control_name: "control"
    col_exp: "#E63946"
  H2O2:
    dir_proteomics: "H2O2"
    condition: "H2O2_phosph"
    norm_opt: "not_norm"
    col_control: "#4f4f4f"
    control_name: "control"
    col_exp: "#04839F"
  Arsenite:
    dir_proteomics: "Arsenite"
    condition: "Arsenite_phosph"
    norm_opt: "not_norm"
    col_control: "#4f4f4f"
    control_name: "control"
    col_exp: "#8CB63E"
  DEX:
    dir_proteomics: "DEX"
    condition: "DEX_phosph"
    norm_opt: "not_norm"
    col_control: "#4f4f4f"
    control_name: "control"
    col_exp: "#F18F01"
